plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'org.sonarqube' version '7.4.0.8496'
}

group = 'br.com.refactoring-lab'
version = '0.0.1-SNAPSHOT'
description = 'refactoring-lab'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Web / MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Persistência & Mensageria
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    // Suporte a Suíte Local via Docker Compose
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

    // Testes
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}

// Configuração de execução e validação dos testes
test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

// Geração de relatórios de cobertura
jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
    finalizedBy jacocoTestCoverageVerification
}

// Regra para exigir % mínima de cobertura local/build
jacocoTestCoverageVerification {
    dependsOn jacocoTestReport
    violationRules {
        rule {
            element = 'BUNDLE'
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.30 // Exige 80% de cobertura de linhas
            }
        }
    }
}

// Envio dos dados para o SonarCloud
sonar {
    properties {
        property "sonar.projectKey", "tiagohenriqueramos_refactoring-lab"
        property "sonar.organization", "tiagohenriqueramos"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
        property "sonar.gradle.skipCompile", "true"
      //  property "sonar.qualitygate.wait", "true" // Trava a pipeline no GitHub caso o Sonar reprove o Quality Gate
    }
}