plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'org.sonarqube' version '5.1.0.4882'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}

test {
    finalizedBy jacocoTestReport // Garante que o relatório do JaCoCo é gerado logo após os testes
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true // O Sonar precisa do XML habilitado
        html.required = true
    }
}

sonar {
    properties {
        property "sonar.projectKey", "tiagohenriqueramos_refactoring-lab"
        property "sonar.organization", "tiagohenriqueramos"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
        property "sonar.gradle.skipCompile", "true"
    }
}

group = 'br.com.refactoring-lab'
version = '0.0.1-SNAPSHOT'
description = 'refactoring-lab'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Web / MVC
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Persistência & Mensageria
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'

    // Suporte a Suíte Local via Docker Compose
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

    // Testes
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}